var header="";
header += "    <nav class=\"navbar navbar-expand-lg navbar-dark \" style=\"background-color: rgb(14, 46, 100);\">";
header += "      <div class=\"container-fluid\">";
header += "          <a class=\"navbar-brand \" href=\"index.html\">啟勝電機行<\/a>";
header += "          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\">";
header += "              <span class=\"navbar-toggler-icon\"><\/span>";
header += "          <\/button>";
header += "          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">";
header += "              <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"index.html\">Home<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"new_order.html\">新增訂單<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"new_purchase_order.html\">訂單彙整<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"goods_check.html\">盤點確認<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"exchange.html\">換貨<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"exchange_check.html\">換貨到貨<\/a>";
header += "                  <\/li>";
header += "              <\/ul>";
header += "              <span class=\"navbar-text me-3\">採購系統<\/span>";
header += "              <a href=\"../login.html\">";
header += "              <button class=\"btn btn-secondary\">登出<\/button>";
header += "              <\/a>";
header += "          <\/div>";
header += "      <\/div>";
header += "  <\/nav>";