var header="";
header += "    <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">";
header += "      <div class=\"container-fluid\">";
header += "          <a class=\"navbar-brand \" href=\"purchase_index.php\">啟勝電機行<\/a>";
header += "          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\">";
header += "              <span class=\"navbar-toggler-icon\"><\/span>";
header += "          <\/button>";
header += "          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">";
header += "              <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_index.php\">Home<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_new_order.php\">新增訂單<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_new_purchase_order.php\">訂單彙整<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                    <a class=\"nav-link\" href=\"purchase_purchasing.php\">採購<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_goods_check.php\">盤點確認<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_exchange.php\">換貨<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"purchase_exchange_check.php\">換貨到貨<\/a>";
header += "                  <\/li>";
header += "              <\/ul>";
header += "              <span class=\"navbar-text me-3\">採購系統<\/span>";
header += "              <a href=\"logout.php\">";
header += "              <button class=\"btn btn-secondary\">登出<\/button>";
header += "              <\/a>";
header += "          <\/div>";
header += "      <\/div>";
header += "  <\/nav>";
