var header="";
header += "<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">";
header += "      <div class=\"container-fluid\">";
header += "          <a class=\"navbar-brand \" href=\"shipment_index.php\">啟勝電機行<\/a>";
header += "          <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\">";
header += "              <span class=\"navbar-toggler-icon\"><\/span>";
header += "          <\/button>";
header += "          <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">";
header += "              <ul class=\"navbar-nav me-auto mb-2 mb-lg-0\">";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"shipment_index.php\">Home<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"shipment_stock_up.php\">備貨<\/a>";
header += "                  <\/li>";
header += "                  <li class=\"nav-item\">";
header += "                      <a class=\"nav-link\" href=\"shipment_shipping.php \">出貨<\/a>";
header += "                  <\/li>";
header += "              <\/ul>";
header += "              <span class=\"navbar-text me-3\">出貨系統<\/span>";
header += "              <a href=\"logout.php\">";
header += "              <button class=\"btn btn-secondary\">登出<\/button>";
header += "              <\/a>";
header += "          <\/div>";
header += "      <\/div>";
header += "  <\/nav>";
